version: 2.1

orbs:
  android: circleci/android@1.0.3

make_property_file: &make_property_file
  run:
    name: Make Property File
    command: |
      EXT_PROPERTIES=ext.properties
      echo "CURRENCY_LAYER_KEY=$CURRENCY_LAYER_KEY" >> $EXT_PROPERTIES
      echo "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN" >> $EXT_PROPERTIES

jobs:
  unit-test:
    docker:
      - image: circleci/android@sha256:061e2535826cc3fe4c4a440e716bf06c36c80401ee635c339c6803b3e427ebb3
    steps:
      - checkout
      - <<: *make_property_file
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew testDebug jacocoFullReport coverallsJacoco --stacktrace
      - android/save-gradle-cache
      - android/save-build-cache
      - store_artifacts:
          path: ./build/reports/jacoco/html/
          destination: reports

workflows:
  test:
    jobs:
      - unit-test